### ISSUE TITLE
No such operator torch_sparse::hetero_neighbor_sample

### ISSUE THREAD

**Issue by senllh** [ytchx1999/OGBN-MAG-PyG2.0#1]
**### Hello, i have suffer some trouble when i run your code.

When i use the version of torch_sparse<=0.6.11, have the error as follow:**

  File "D:/PyG/OGBN-MAG-PyG2.0-main/src/main.py", line 149, in <module>
    main()
  File "D:/PyG/OGBN-MAG-PyG2.0-main/src/main.py", line 71, in main
    train_loader = NeighborLoader(data, num_neighbors=[args.num_neighbors, args.num_neighbors], input_nodes=train_input_nodes, shuffle=True, **kwargs)
  File "D:\anaconda\lib\site-packages\torch_geometric\loader\neighbor_loader.py", line 159, in __init__
    self.sample_fn = torch.ops.torch_sparse.hetero_neighbor_sample
  File "D:\anaconda\lib\site-packages\torch\_ops.py", line 60, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator torch_sparse::hetero_neighbor_sample

**When i update the version of torch_sparse to 0.6.12, have the error as follow:**

Traceback (most recent call last):
  File "D:/PyG/OGBN-MAG-PyG2.0-main/src/main.py", line 149, in <module>
    main()
  File "D:/PyG/OGBN-MAG-PyG2.0-main/src/main.py", line 81, in main
    init_params(model, train_loader, device)
  File "D:\anaconda\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "D:/PyG/OGBN-MAG-PyG2.0-main/src/main.py", line 40, in init_params
    batch = next(iter(train_loader))
  File "D:\anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 354, in __iter__
    self._iterator = self._get_iterator()
  File "D:\anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "D:\anaconda\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\anaconda\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\anaconda\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\anaconda\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'PyCapsule' object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\anaconda\lib\multiprocessing\spawn.py", line 128, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by senllh** [comment]
I'm in desperate need of your help. Thank you!

**Comment by ytchx1999** [comment]
> 

![image](https://user-images.githubusercontent.com/54234005/150668321-0a55812f-5bcf-44f4-9775-d73a2314b3f5.png)

This is my torch_scatter version.

"EOFError: Ran out of input" -- I think it is a file error, try downloading the dataset again?
